set_property PACKAGE_PIN Y9 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports Reset]
set_property IOSTANDARD LVCMOS33 [get_ports foundDatainCache_core]
set_property PACKAGE_PIN T21 [get_ports foundDatainCache_core]
set_property PACKAGE_PIN H22 [get_ports Reset]
